### ISSUE TITLE
swift 3 Xcode8 beta6 Open class

### ISSUE THREAD

**Issue by joaoAvno** [goktugyil/EZSwipeController#35]
in last xcode version i got this error "Overriding non-open instance method outside of its defining module" in  setup method 

override func setupView() {
        super.setupView()
        datasource = self
        navigationBarShouldNotExist = true
        view.backgroundColor = UIColor(red: 231/255, green: 231/255, blue: 231/255, alpha: 1)
    }

any idea how to solve this?

**Comment by gkermo** [comment]
I had the same issue, I modified `EZSwipeController.swift`, setting the class as `open` instead of `public` ( c.f. : [SE-0117 Allow distinguishing between public access and public overridability](https://github.com/apple/swift-evolution/blob/master/proposals/0117-non-public-subclassable-by-default.md) ).

It solved the problem.

**Comment by JFKingsley** [comment]
This should be fixed in the latest release.
